package utils

var ProducerNames = []string{`ООО "Озон"`, "Озон ООО/Озон Фарм ООО", "Озон ООО", "Озон Фарм ООО"}

var Regions = map[string]string{
	"moscowregion": "Москва и область",
	"spb":          "Санкт-Петербург и область",
	"novosibirsk":  "Новосибирск",
	"ekb":          "Екатеринбург",
	"kazan":        "Казань",
	"nnovgorod":    "Нижний Новгород",
	"ufa":          "Уфа",
	"rostov":       "Ростов-на-Дону",
}

var PillsList = map[string]string{
	"antistenMV":                 "Антистен",
	"artrafik":                   "артрафик",
	"cerpehol":                   "Церпехол",
	"citipigam":                  "Цитипигам",
	"detravenol":                 "Детравенол",
	"doksiciklin":                "Доксициклин",
	"jekurohol":                  "Экурохол",
	"jekziter":                   "Экзитер",
	"jeljufor":                   "Элюфор",
	"esslial":                    "эсслиал форте",
	"estetatet":                  "эстет а тет",
	"jezlor":                     "Эзлор",
	"fazostabil":                 "Фазостабил",
	"flebofa":                    "Флебофа",
	"frejmitus":                  "Фреймитус",
	"holikron":                   "Холикрон",
	"izislip":                    "Изислип",
	"kontrazud":                  "Контразуд",
	"ksilometazolin":             "Ксилометазолин",
	"kruoksaban":                 "круоксабан",
	"magnepasit":                 "Магнепасит",
	"mebespalin":                 "Мебеспалин",
	"meladapt":                   "Меладапт",
	"memoritab":                  "Меморитаб",
	"motilorus":                  "Мотилорус",
	"mukocil":                    "Мукоцил",
	"naftoderil":                 "Нафтодерил",
	"nekspra":                    "Некспра",
	"nikurilly":                  "Никуриллы",
	"noocil":                     "Нооцил",
	"orungamin":                  "Орунгамин",
	"pronokognil":                "Пронокогнил",
	"safiston":                   "Сафистон",
	"seltavir":                   "Сельтавир",
	"skinoklir":                  "Скиноклир",
	"sumatrolid":                 "Суматролид",
	"tiloram":                    "Тилорам",
	"tolizor":                    "Толизор",
	"toraksol-soljushn-tablets":  "Тораксол солюшн таблетс",
	"ulblok":                     "Ульблок",
	"vildegra":                   "Вилдегра",
	"vismuta-trikalija-dicitrat": "Висмута трикалия дицитрат",
}
